name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build all binaries
        run: |
          bun run build:linux
          bun run build:windows
          bun run build:macos-intel
          bun run build:macos-arm

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/

  changelog:
    name: Generate changelog
    uses: ./.github/workflows/changelog.yml

  create-release:
    name: Create GitHub Release
    needs: [build, changelog]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ needs.changelog.outputs.changelog }}
          files: artifacts/**/*
          make_latest: true
